// components
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/Footer/Footer";
// fonts
import type { Metadata } from "next";
// styles
import "./globals.css";
// others
import { Urbanist } from "next/font/google";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Navbar />
        <div className="main-container">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
